version: '3.8'
services:
  python:
    build:
      context: .
    container_name: app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg:5432/test_db
    ports:
      - "8080:8080"
  sql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
