version: '3.9'
name: measurements
services:
  python:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d