version: '3.8'
services:
  python:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
  sql:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
