FROM python:3.11-slim-buster

WORKDIR /app

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

COPY requirements.txt ./

COPY entrypoint-heroku.sh /

RUN pip install -r requirements.txt

EXPOSE 8080

COPY app/ ./

CMD ["/entrypoint-heroku.sh"]