version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hanagotchi
      POSTGRES_PASSWORD: nfVH3f3KtgoD
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d