version: '3.9'
name: measurements
services:
  python:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d